pkgname="db"
output="graph/db"
wipe=true
add-global-variants=false
no-tests=true

[psql]
  dbname = "review_pull_request"
  host   = "localhost"
  port   = 5434
  user   = "user"
  pass   = "dbpass"
  sslmode= "disable"
  blacklist = []
